spring.application.name=easybank_api

# Dtabase connection
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/easybank
spring.datasource.username=postgres
spring.datasource.password=pepeesmufeo15.

# JPA and Hibernate. First one to update database when any entity changes. To validate first, use validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

# Config: It uses default values for given null properties, for example, when form data does not have a property
# https://stackoverflow.com/questions/79854395/spring-boot-4-jackson-deserialization-behaves-differently-cannot-map-null-into
spring.jackson.deserialization.fail-on-null-for-primitives=false   