spring.application.name=easybank_api

# Conexión base de datos
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/easybank
spring.datasource.username=postgres
spring.datasource.password=pepeesmufeo15.

# JPA e Hibernate. La primera es para actualizar con cambios cada vez que arrancamos la app, validate para producción
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true