## Get all messages
GET http://localhost:8080/api/message
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcHprNlR4WUtyIiwiaWF0IjoxNzkwMDE3MTc5LCJleHAiOjE3OTAwMTg5Nzl9.g9o6wMGHw9NfQoinkF0wCZ5MkQ5WbD5e7iPnk5pZVWc

