### Create operation
POST http://localhost:8080/api/client/operation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcHprNlR4WUtyIiwiaWF0IjoxNzg5ODM0NDY0LCJleHAiOjE3ODk4MzYyNjR9.TuQ5gqKmbLAWaxkhWIKe7iwfUdej9wH96BE9RlU-PHE

{
  "concept": "prueba redis desde client rest 2",
  "accountId": "f5e0bee5-681b-4039-9944-f2bda1b82ddf",
  "operationType": "TRANSFER",
  "beneficiaryAccount": "ES3400011234246855039185",
  "amount": 0.01
}

### Authorize operation by operationId
POST http://localhost:8080/api/client/operation/authorize/ede6360e-25f5-4222-87be-ad42702bff3b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcHprNlR4WUtyIiwiaWF0IjoxNzg5ODM0NDY0LCJleHAiOjE3ODk4MzYyNjR9.TuQ5gqKmbLAWaxkhWIKe7iwfUdej9wH96BE9RlU-PHE

{
  "pin": "12345"
}