### Get all users
GET http://localhost:8080/api/admin/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpSzUxcnJKcEFLIiwiaWF0IjoxNzkwODA1NzgyLCJleHAiOjE3OTA4MDc1ODJ9.ykXyONIrAO-_c4KHdzuvxLtSFyYzmtTz_AyQamw82FQ

### Get user by id
GET http://localhost:8080/api/admin/user/d5fb388a-c86b-4238-aaf2-fa81edb54ec8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpSzUxcnJKcEFLIiwiaWF0IjoxNzkwNzA1Mjc2LCJleHAiOjE3OTA3MDcwNzZ9.J2AHnIFyny8OroUcZ18GOK5C7zo-kiZWYWo2VlPQwlU

### Creates a new user
POST http://localhost:8080/api/admin/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpSzUxcnJKcEFLIiwiaWF0IjoxNzkwODA2ODkwLCJleHAiOjE3OTA4MDg2OTB9.RF6LU5i2MkKgulQGsJ1ppRqTW0b3dQ5l7XIn_kgRLp4

{
  "name": "Pepe",
  "surname": "González",
  "dni": "87528222C",
  "email": "user@example.com",
  "phone": "666786655",
  "password": "nuevacontrasena",
  "repeatPassword": "nuevacontrasena",
  "role": "CLIENT",
  "status": "ENABLED"
}

### Updates an existent user
PATCH http://localhost:8080/api/admin/user/51cfd504-8734-4ba6-8bb1-52295da5aca9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpSzUxcnJKcEFLIiwiaWF0IjoxNzkwODA2ODkwLCJleHAiOjE3OTA4MDg2OTB9.RF6LU5i2MkKgulQGsJ1ppRqTW0b3dQ5l7XIn_kgRLp4

{
  "name": "Juan",
  "surname": "Canales",
  "dni": "87528222C",
  "email": "pepe@gmail.com",
  "phone": "654234123",
  "requestUsercode": true,
  "pin": "1234",
  "password": "stringggg",
  "role": "ADMIN",
  "status": "ENABLED"
}

### Deletes an user
DELETE http://localhost:8080/api/admin/user/88aa4ccc-2d9e-4e46-be2b-af239ab0ca9d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpSzUxcnJKcEFLIiwiaWF0IjoxNzkwODA1OTI3LCJleHAiOjE3OTA4MDc3Mjd9.jlw37MXaz8mgTXTym88ALhl_XUnCacxYSvpv_U8M7J4
